import { Link } from 'react-router-dom';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-2">
      <h2 className="text-lg font-semibold text-slate-900 dark:text-white">{title}</h2>
      <div className="text-sm leading-relaxed text-slate-600 dark:text-white/70 space-y-2">{children}</div>
    </section>
  );
}

export default function Terms() {
  return (
    <div className="min-h-screen bg-white dark:bg-[#0B0C12]">
      <main className="mx-auto max-w-3xl px-6 py-12 space-y-8">
        <header className="space-y-2">
          <Link to="/" className="text-xs font-semibold text-indigo-600 dark:text-indigo-400 hover:underline">
            ← Back to Carol Ann
          </Link>
          <h1 className="text-3xl font-bold text-slate-900 dark:text-white">Terms of Service</h1>
          <p className="text-xs text-slate-500 dark:text-white/40">Last updated: September 2026</p>
        </header>

        <Section title="The service">
          <p>
            Carol Ann is a women's platform — a personal AI companion and workspace app. These terms are the
            agreement between you and us for using it.
          </p>
        </Section>

        <Section title="Your account">
          <p>
            You need an account to use Carol Ann. You are responsible for keeping your sign-in credentials safe
            and for everything done under your account. You must be able to form a binding agreement to use
            the service (generally, of legal age in your location).
          </p>
        </Section>

        <Section title="AI-generated content">
          <p>
            Carol Ann's responses are generated by AI. They can be wrong, incomplete, or out of date. They are
            advisory only — verify anything important before acting on it.
          </p>
          <p>
            Carol Ann is not a substitute for professional advice. It does not provide medical, legal, financial,
            or other professional services. If you need those, consult a qualified professional.
          </p>
        </Section>

        <Section title="Demo features">
          <p>
            Features labeled as a demo or sandbox (such as the connector directory) are simulations. They do not
            connect to outside services, move money, post content, or take real-world actions.
          </p>
        </Section>

        <Section title="Acceptable use">
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Use Carol Ann for anything unlawful or to harm others.</li>
            <li>Try to break into, overload, or misuse the service or other users' workspaces.</li>
            <li>Misrepresent AI-generated content as human-created or as professional advice.</li>
            <li>Resell or repackage the service without permission.</li>
          </ul>
        </Section>

        <Section title="Availability">
          <p>
            We work to keep Carol Ann available, but we do not guarantee uninterrupted service. Features may
            change or be removed as the product evolves.
          </p>
        </Section>

        <Section title="Limitation of liability">
          <p>
            To the fullest extent the law allows, Carol Ann is provided "as is," and we are not liable for
            indirect or consequential damages arising from your use of the service.
          </p>
        </Section>

        <Section title="Changes to these terms">
          <p>
            If these terms change in a meaningful way, we will note it in the app. Continued use after a change
            means you accept the updated terms.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions about these terms? Reach us through the feedback channel inside the app and we will respond.
          </p>
        </Section>
      </main>
    </div>
  );
}
